// lib/firebase_options.dart
// ============================================================
// Generated by FlutterFire for the Silarah Firebase project.
// Regenerate this file together with the native Firebase files when switching
// dev/staging/prod Firebase projects.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Firebase web config is not enabled.');
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Firebase is configured only for Android and iOS builds.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGKqQtW9lsVOgpls3tPjGUdoC6jVbJ0ws',
    appId: '1:163379661830:android:062cb833b274c89dedc787',
    messagingSenderId: '163379661830',
    projectId: 'mithaq-fcf44',
    storageBucket: 'mithaq-fcf44.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCW4nNYSSUxjEixqd3GelQA0bqqoqeg4I',
    appId: '1:163379661830:ios:67c3ea4e7a96b040edc787',
    messagingSenderId: '163379661830',
    projectId: 'mithaq-fcf44',
    storageBucket: 'mithaq-fcf44.firebasestorage.app',
    iosBundleId: 'com.silarah.app',
  );
}
