-- ============================================================
-- MIGRATION 031: BLURHASH SUPPORT
-- Add blurhash column to photos table and discovery_pool view.
-- ============================================================

-- 1. Add blurhash column to photos table
ALTER TABLE photos
  ADD COLUMN IF NOT EXISTS blurhash text;

COMMENT ON COLUMN photos.blurhash IS
  'BlurHash string (~30 bytes) encoding a blurred color preview of the photo. '
  'Generated by the validate-photo-upload Edge Function when the photo is activated. '
  'Used client-side to render a smooth placeholder during image load.';

-- 2. Drop and recreate discovery_pool materialized view to include blurhash
DROP MATERIALIZED VIEW IF EXISTS discovery_pool;

CREATE MATERIALIZED VIEW discovery_pool AS
SELECT
  p.id                                               AS profile_id,
  p.user_id,
  p.gender,
  p.visibility,
  p.onboarding_step,
  p.first_name,
  LEFT(p.last_name, 1)                               AS last_name_initial,
  EXTRACT(YEAR FROM age(p.date_of_birth))::integer   AS age,
  c.name                                             AS city_name,
  p.country_code,
  c.id                                               AS city_id,
  p.sect::text,
  p.sub_sect,
  p.deen_level::text,
  p.profession,
  p.bio,
  p.static_rank_score                                AS rank_score,
  p.last_active_at,
  p.location,
  ST_Y(p.location::geometry)                         AS lat,
  ST_X(p.location::geometry)                         AS lng,
  p.photo_privacy::text,
  p.is_verified,
  p.education_rank,
  p.height_cm,
  p.date_of_birth,
  p.approved_at,
  p.is_boosted,
  p.boost_expires_at,
  p.complexion,
  p.mother_tongue,
  p.community,
  p.residency_status,
  p.diet_type,
  p.smoking_habit,
  p.quran_memorization,
  p.religious_education,
  p.marriage_timeline,
  p.willing_to_relocate,
  p.living_expectation,
  p.is_revert,
  p.special_needs,
  p.previously_married,
  p.children_count,
  p.family_type,
  p.niqab_preference,
  p.mahr_expectation,
  p.mahr_budget,
  p.can_provide_housing,
  p.can_provide_maintenance,
  p.polygamy_status,
  p.listens_to_music,
  p.eats_zabiha_only,
  p.attends_islamic_classes,
  p.reads_quran_daily,
  p.celebrates_mawlid,
  p.watches_movies,
  p.gender_mixing_stance,
  -- Photo count
  (
    SELECT COUNT(*)::integer
    FROM photos ph
    WHERE ph.profile_id = p.id
      AND ph.admin_approved = true
      AND ph.nsfw_cleared   = true
  )                                                  AS photo_count,
  -- photo_url (first photo storage path)
  (
    SELECT CASE WHEN p.photo_privacy = 'public' THEN ph.storage_path ELSE NULL END
    FROM photos ph
    WHERE ph.profile_id   = p.id
      AND ph.order_index  = 0
      AND ph.admin_approved = true
      AND ph.nsfw_cleared   = true
    LIMIT 1
  )                                                  AS photo_url,
  -- photo_blurhash (first photo blurhash)
  (
    SELECT CASE WHEN p.photo_privacy = 'public' THEN ph.blurhash ELSE NULL END
    FROM photos ph
    WHERE ph.profile_id   = p.id
      AND ph.order_index  = 0
      AND ph.admin_approved = true
      AND ph.nsfw_cleared   = true
    LIMIT 1
  )                                                  AS blurhash,
  -- Preference fields
  pr.diaspora_mode,
  pr.open_to_diaspora,
  pr.preferred_countries,
  pr.preferred_age_min,
  pr.preferred_age_max,
  pr.min_education_rank,
  pr.deen_preference,
  pr.preferred_mother_tongue,
  pr.preferred_community,
  pr.preferred_height_min,
  pr.preferred_height_max,
  pr.preferred_marriage_timeline,
  pr.preferred_relocation,
  pr.preferred_living_expectation,
  pr.polygamy_acceptance  AS pref_polygamy_acceptance,
  pr.revert_acceptance,
  pr.special_needs_acceptance,
  pr.pref_music_stance,
  pr.pref_zabiha_only,
  pr.pref_quran_daily,
  pr.pref_gender_mixing
FROM profiles p
JOIN cities c ON p.city_id = c.id
JOIN profile_preferences pr ON p.id = pr.profile_id
WHERE p.visibility    = 'visible'
  AND p.onboarding_step >= 14;

-- Recreate indexes
CREATE UNIQUE INDEX idx_discovery_pool_id       ON discovery_pool(profile_id);
CREATE INDEX         idx_discovery_pool_location ON discovery_pool USING GIST (location);
CREATE INDEX         idx_discovery_pool_rank     ON discovery_pool(rank_score DESC, profile_id DESC);
CREATE INDEX         idx_discovery_pool_gender   ON discovery_pool(gender);
CREATE INDEX         idx_discovery_pool_country  ON discovery_pool(country_code);
CREATE INDEX IF NOT EXISTS idx_discovery_pool_gender_country_rank
  ON discovery_pool(gender, country_code, rank_score DESC);

COMMENT ON MATERIALIZED VIEW discovery_pool IS
  'V5: Added blurhash column to support progressive photo placeholders.';
